CREATE TABLE users_passwords (
  id BIGINT NOT NULL AUTO_INCREMENT,
  password_hash VARBINARY(60) NOT NULL,
  user_id BIGINT NOT NULL,

  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);
